name: GitHub Action CI

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Print working dir
      run: |
        Write-Host "wd=$Env:GITHUB_WORKSPACE
        $c = Get-Content "$PSScriptRoot\..\RELEASENOTES.md" -Encoding UTF8
        $firstLine = $c[0]
        $version = $firstLine -replace '- *([^ ]*).*', '$1'
        if(-not $version) {
            throw "Could not extract version tag from RELEASENOTES.md"
        }
        Write-Host "Using version tag extracted from release notes: $version"
    - name: Infer version from release notes
      run: |
        $version = & ./Get-Version.ps1
        echo "NUGET_PACKAGE_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.0.0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

          
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore --no-incremental
    - name: Test
      run: dotnet test --no-restore --verbosity normal --no-build
